$(function(){
	$("#form_regist").validate({
		rules:{
			username:{
				required:true,
				rangelength:[6,20],
				remote:{
					url:"/voc_info/checkUsername",
					type:"post",
					dataType:"json",
					data:{username:function(){return $("#username").val();}}
				}
			},
			password:{
				required:true,
				rangelength:[6,20]
			},
			password2:{
				required:true,
				rangelength:[6,20],
				equalTo:"#password"
			},
			nickname:{
				required:true
			},
			email:{
				required:true,
				email:true
			}
		},
		messages:{
			username:{
				required:"<i></i>用户名不能为空",
				rangelength:"<i></i>用户名长度必须在6-20之间",
				remote:"<i></i>用户名已存在"
			},
			password:{
				required:"<i></i>密码不能为空",
				rangelength:"<i></i>密码长度必须在6-20之间"
			},
			password2:{
				required:"<i></i>密码确认不能为空",
				rangelength:"<i></i>密码确认长度必须在6-20之间",
				equalTo:"<i></i>两次输入的密码不一致"
			},
			nickname:{
				required:"<i></i>昵称不能为空"
			},
			email:{
				required:"<i></i>邮箱不能为空",
				email:"邮箱格式不正确！"
			}
		},
		errorPlacement:function(error,element){
			error.appendTo(element.parent().next("div"));
		},
		onkeyup:false,
		errorClass:"error",
		success:function(label){
			label.addClass("valid").html("<i></i>");
		}
	});
});